### ISSUE TITLE
minor typo in "common" snippet

### ISSUE THREAD

**Issue by warren-bank** [textileio/docs#118]
* links:
  - [yaml in repo](https://github.com/textileio/docs/blob/50012b69a3e5954a6e5e9afe90d3829877053fc2/snippets/common.yml#L94)
  - [rendered html in docs](https://docs.textile.io/a-tour-of-textile/#share-a-thread)
* current value:
  ```text
      code: 'textile init "$(textile wallet init | tail -n1)" --repo="/tmp/buddy" --swarm-ports="4101" --api-bind-addr="127.0.0.1:41600" --gateway-bind-addr="127.0.0.1:5150 --profile-bind-addr="127.0.0.1:6061""'
  ```
* fixed parameter quotes:
  ```text
      code: 'textile init "$(textile wallet init | tail -n1)" --repo="/tmp/buddy" --swarm-ports="4101" --api-bind-addr="127.0.0.1:41600" --gateway-bind-addr="127.0.0.1:5150" --profile-bind-addr="127.0.0.1:6061"'
  ```
* summary:
  - `--gateway-bind-addr` closing quote incorrectly positioned at end of `--profile-bind-addr`

**Comment by andrewxhill** [comment]
all new docs out! this should all be replaced now.
