### ISSUE TITLE
minor typo in "a-tour-of-textile.md"

### ISSUE THREAD

**Issue by warren-bank** [textileio/docs#119]
* file:
  - [a-tour-of-textile.md](https://github.com/textileio/docs/blob/50012b69a3e5954a6e5e9afe90d3829877053fc2/docs/a-tour-of-textile.md)
* search: `Gateway address: 127.0.0.1:5050`
  - should only find 1 match
* replace: `Gateway address: 127.0.0.1:9090`
  - as this is the `cmd` output after restarting the daemon to accept a [config change to the gateway port](https://docs.textile.io/a-tour-of-textile/#set-a-config-value)

**Comment by andrewxhill** [comment]
thanks for your edits. retired the tour for now, so easy solution. :)
