### ISSUE TITLE
Write all the docs

### ISSUE THREAD

**Issue by sanderpick** [textileio/docs#12]
Renaming this one to... just "write all the docs"

**Comment by sanderpick** [comment]
TO-DO:

- [ ] Finish "A Tour of Textile" (@sanderpick)
- [ ] Update threads page (@sanderpick)
- [ ] Update wallet page (@sanderpick)
- [ ] Add contacts page (@sanderpick)
- [ ] Update the config file page (@sanderpick)
- [ ] Pull in react native docs (@asutula)
- [ ] Pull in js-http-textile docs (@carsonfarmer)
- [ ] Pull in iOS docs (@asutula)
- [ ] Pull in Android docs (@asutula)

Related go-textile tweaks that need to happen (issues to come if they don't already exist):
- [ ] Merge command-line tweaks branch created when writing tour
- [ ] Grab public IP address for cafes from the announce config (basically, try to remove the requirement that the user needs to manually specify the machines public IP)
- [ ] Allow setting an avatar via path (tour already says you can do this... the current setup is too confusing to even write up)

**Comment by sanderpick** [comment]
More go-textile tweaks:
- [ ] Rename `f` and `d` links to `meta` and `data` (good point @balupton)
- [ ] Use the account thread for avatars

**Comment by balupton** [comment]
> * [ ]  Rename `f` and `d` links to `meta` and `data` (good point @balupton)
> *

Perhaps `meta` and `content` would be better, as distinguishing meta and data in the same sentence could be confusing.

**Comment by sanderpick** [comment]
I like it. It is indeed a mouthful to talk about "meta" and "data" and then the fact that "meta" is "metadata"

**Comment by sanderpick** [comment]
closing this in favor of more specific issues
