### ISSUE TITLE
As an invited member of a team, how to retrieve project files.

### ISSUE THREAD

**Issue by nlko** [textileio/docs#123]
Hello,

Reading the tour of the new textile I can't understand how I can retrieve the files from a project of a team I was just invited to.

Do the files of the project need to be exported to a bucket first ? It's not clear what I need to do.

Maybe the documentation could be updated to better describe this use case.

Thanks for all the work,

Nicolas

**Comment by andrewxhill** [comment]
hi @nlko sorry for the delay on response here. we've just released a new architecture for accounts. there are no more Projects. just devs, orgs, and buckets. https://docs.textile.io is up to date.
