### ISSUE TITLE
nav menu gets scrambled when collapsed

### ISSUE THREAD

**Issue by asutula** [textileio/docs#125]
if I collapse a section of the menu, it looks like:
<img width="259" alt="Screen Shot 2020-04-29 at 11 40 12 AM" src="https://user-images.githubusercontent.com/528969/80622419-619bd800-8a0e-11ea-9095-f93ac57e800a.png">

**Comment by andrewxhill** [comment]
shucks. i see some of that, only on safari. in particular, the chevrons don't move up when the rest collapses.

<img width="175" alt="Screen Shot 2020-04-29 at 6 57 30 PM" src="https://user-images.githubusercontent.com/370259/80664301-47ccb600-8a4b-11ea-9681-bd3f9b7edf3e.png">

that's testing master, where it seems to have the same problem. safari only though

**Comment by andrewxhill** [comment]
fixed this in pr

**Comment by andrewxhill** [comment]
here's the fix https://github.com/textileio/docs/blob/master/material/base.html#L169 

🤷
