### ISSUE TITLE
Complete example on using ThreadsDB and creating a Database

### ISSUE THREAD

**Issue by theefer** [textileio/docs#131]
All the code samples for ThreadsDB omit key parts that make it very hard to know how to use the API in practice.

The [databases](https://docs.textile.io/threads/introduction/#databases), collections, etc examples all omit the details of Database creation (`new Database(...)`). The [multi-user threads](https://docs.textile.io/threads/introduction/#databases) seems to give a few hints but it's not clear whether it's canonical use. The only example I found was in the [react-3box-threadsdb example](https://github.com/textileio/js-examples/blob/master/react-3box-threadsdb/src/Store/Actions.ts#L8), but again it's not clear whether it's the simplest canonical use.

**Comment by carsonfarmer** [comment]
See also https://github.com/textileio/js-threads/issues/63
