### ISSUE TITLE
Update for hub + buck binaries

### ISSUE THREAD

**Issue by asutula** [textileio/docs#171]
The Hub section of the docs still mentions `tt`, uses `hub` some, and doesn't say anything about the `buck` binary. This should be updated to be consistent with the current releases.

**Comment by andrewxhill** [comment]
i'm intentionally not adding the buck binary for now. we have too big a support surface area, so we are leaving it for the brave. we'll revisit that in the future.

re. `tt` i tried to get them all but must have missed some. i looked again and found a couple more. but if you have specific refs that would help a lot.

**Comment by andrewxhill** [comment]
fixed 2 found in account section

**Comment by andrewxhill** [comment]
https://github.com/textileio/docs/pull/170
