### ISSUE TITLE
Error: "Not enough miners that satisfy the constraints" on Devnet server

### ISSUE THREAD

**Issue by peterVG** [textileio/docs#174]
On `docs/powergate/ffs.md` in the "initiate storage" section I ran the `pow ffs push --watch <cid>` command against my Powergate Devnet server that is running successfully on Docker. 

I pushed the cid config successfully using the default CidConfig. The docs indicate that I should see a "SUCCESS" status if I follow these steps. However, my cold-storage failed with the following error message:

`> Success! Pushed cid config for QmPeE7KECg4XEdhfMk9fH7DnFEuwpXEnBVNsfeArs5Vy2o to FFS with job id: 3c8808c2-02ae-40c6-bc15-f1757c5b297e
               JOB ID                	                                                                   STATUS                                                                     
3c8808c2-02ae-40c6-bc15-f1757c5b297e	Failed executing cold-storage config: making deal configs: getting miners 
                                                                                from minerselector: not enough miners that satisfy the constraints`

Also, when I check `pow wallet balance --address` for the address given in that CidConfig I get a `Success! Balance: 0`. Is this related? E.g. I have no funds to make a storage deal and there are no miners in my Devnet willing to store for 0 FIL? If so, how do I add a balance to my wallets in the Devnet?

**Comment by samikshan** [comment]
I haven't been able to reproduce this failure with default CID config. Also you seeing a balance of `0 FIL` on your wallet seems weird. I would suggest that you create another FFS instance and retry on that instance for now?

**Comment by peterVG** [comment]
Yeah, I should have thought of that myself (retrying with new FFS instance), thanks. It worked! And the wallet balance for this new instance is 3999997083497587. That's quite a bit more than 0 :-) So I do think that was related to the error message. Thanks for suggestion. Closing this issue.
