### ISSUE TITLE
Javascript Docs redirect on https://docs.textile.io/ leads to 404 page 

### ISSUE THREAD

**Issue by bhflm** [textileio/docs#262]
**Describe the bug**

At [https://docs.textile.io/](https://docs.textile.io/) specifically the **Javascript Docs** link, redirects to a 404 site (https://textileio.github.io/js-threads/) 

![image](https://user-images.githubusercontent.com/23338712/106216672-6d414880-61b2-11eb-8127-344ee03d453f.png)

**To Reproduce**
1. Go to [https://docs.textile.io/](https://docs.textile.io/)
2. Click on Javascript docs
3. See error

**Expected behavior**
Redirect to this repo's readme ?

**Comment by andrewxhill** [comment]
oop, yep. looks like the About section on https://github.com/textileio/js-threads missed an update too
