### ISSUE TITLE
Redact secrets used in the tour

### ISSUE THREAD

**Issue by sanderpick** [textileio/docs#32]

**Comment by sanderpick** [comment]
Do we care about this?

**Comment by andrewxhill** [comment]
what's the concern? are some of the cut/pasteable thus leading to bad setups?

**Comment by sanderpick** [comment]
no, just that if everyone decides to use the seed show in the tour we we'd end up with a bunch of account peers, but maybe that's a good thing.

**Comment by andrewxhill** [comment]
ha, let's see! was thinking you could cut a letter out to make it invalid, thus forcing someone to create their own.
