### ISSUE TITLE
Mixed Use of localhost and 127.0.0.1 in Tour of Textile

### ISSUE THREAD

**Issue by undercase** [textileio/docs#62]
In the Tour of Textile, some example commands use the address `127.0.0.1`, like this:

    textile comments add "Is this an outlier?" --block="QmUvWjstQzR6y7UctRJgVjcKsKzutZoiBsQw6WBXMnmg84" --api="http://127.0.0.1:41600"

While others use its alias, `localhost`, like this:

    textile chat --thread="12D3KooWExn4ut4RV2qHXFSiWb3AfhL2whB8vJgYpnDcmVCG7UBv" --api="http://localhost:41600"

I think it would be clearer to choose one and stick to it throughout the guide, but I'm not sure what the pros and cons of each are, or if it's merely a stylistic decision. If we come to a consensus on which one to use I will update the docs to reflect it.

**Comment by sanderpick** [comment]
Oh, good catch. Let's use `127.0.0.1` as the meaning of `localhost` can vary between OSs and we want to always imply loopback.

**Comment by undercase** [comment]
Okay, I'll include this in my pull request later tonight and tag you for review. Thanks!
