### ISSUE TITLE
Some notes while going through the Tour

### ISSUE THREAD

**Issue by JustMaier** [textileio/docs#66]
Hey All, thanks for the awesome documentation. It's super helpful and you've done a great job at making it easy to get started. As I'm going through it, I ran across a few things I thought I should share:

- When adding locations on windows via CLI, I had to remove the single quotes. Just need to note the issue for Windows.
- When doing the section about sending and accepting invites I ran into a problem finding my buddy peer. I triple checked the Acct Id, and it was all correct. Eventually, after waiting a while and trying again, it found the peer. It might be worth mentioning that they should wait a bit after firing up the buddy node to ensure that it's connected to the network.
- It talks about ignoring the invite and gives the code to do that, but it doesn't provide the code needed to accept the invite, just the success message. (it's `textile invites accept "QmWcd5RoyFBsA65EKiJRNsmhoDLADTgRXdri469Fj9nndN" --api="http://127.0.0.1:41600"`)
- When creating the Cafe Token you need to include `--api="http://127.0.0.1:41600"` or ensure you're working from the terminal with that env variable set. It might be best to just include the flag in the code example.

I'll take a stab at fixing these if you agree on the proposed changes.

**Comment by sanderpick** [comment]
This is great, thank you. Those changes all look spot on except for the third one about invites... the section around [sharing a thread](https://docs.textile.io/a-tour-of-textile/#share-a-thread) has this bit toward the bottom:

![Screen Shot 2019-05-09 at 5 01 17 PM](https://user-images.githubusercontent.com/361000/57494037-6ce57900-727c-11e9-80fd-47d1e01a1e2c.png)

But I could be missing what you mean there.

**Comment by JustMaier** [comment]
You're totally right! I see it there now tool. Must've been a weird rendering bug or something because I could've sworn it wasn't there before.

**Comment by JustMaier** [comment]
OK, just submitted a PR for those things. Thanks for all you guys are doing to provide good instructions.
