### ISSUE TITLE
Add overview of pinning unencrypted files

### ISSUE THREAD

**Issue by andrewxhill** [textileio/docs#69]
The use of plaintext should be more thoroughly explained for cases where threads or apps could benefit from pinning unencrypted data in threads

**Comment by andrewxhill** [comment]
I started this here, https://docs.textile.io/concepts/threads/files/#encryption

But I think an Encryption concept page is the way to go

**Comment by sanderpick** [comment]
Oh, forgot to mention... you had it embedded down in the JSON schema section. I moved to its current home. I'm not sure there's much more to say about it... ?
