### ISSUE TITLE
Add concept page for Feed

### ISSUE THREAD

**Issue by andrewxhill** [textileio/docs#77]
It has some helpful organizational tools for subscribing to updates, but it's not super clear from the API docs alone how to use them. Feels like Feed itself should get a concept page to talk about why a developer would use it and some of the different options.

**Comment by carsonfarmer** [comment]
As in mobile, I’m using the feed API on desktop. On desktop, I’m using the stacks mode. This is nice for social feeds, but has some non-intuitive behavior. Not sure if that’s just a docs issue, or worth it’s own issue in go-textile. 

The main thing is updates with a ‘target’ (say a like), can end up in the main feed. But then they are _not_ shown with the their target. This is ok, unless you are having a ‘threaded’ conversation in comments. Which leads to parts of the conversation ending up in different parts of the feed. Perhaps a hybrid option is possible?

**Comment by carsonfarmer** [comment]
After some (re)- evaluation, it seems clear that the 'annotated' mode in the Feed API is most useful for things like on-going (possibly threaded) conversations, and similar use-cases. Creating a concept page for Feed would be a good idea, as we can include this type of information there.
