### ISSUE TITLE
Update command-line client docs

### ISSUE THREAD

**Issue by sanderpick** [textileio/docs#88]
https://docs.textile.io/develop/clients/command-line

We'll need to figure out how to make the nice table of contents for each command (and sub-commands indented) now that the tool doesn't spit out markdown.

**Comment by balupton** [comment]
Isn't the table of contents automatically generated from the h* elements? If so, nothing we need to do.

**Comment by sanderpick** [comment]
I'm just not familiar with how you're rendering it. So, if you've done the indentation, sweet! In any case, we still need to update the content.

**Comment by balupton** [comment]
Rendered via `<h*>` elements followed by a `<p>` element for help text, followed by a `<table>` element for args and flags

**Comment by sanderpick** [comment]
This is a priority. Added to Sprint 13.
