### ISSUE TITLE
Update tour with new command-line usage

### ISSUE THREAD

**Issue by sanderpick** [textileio/docs#89]
I am not sure if there are updates needed here in the tour (https://docs.textile.io/a-tour-of-textile/) w/ the new command-line tool. Seems likely. 

Children:

- [x] https://github.com/textileio/go-textile/issues/783
- [x] https://github.com/textileio/go-textile/issues/793
  - [x] handled by https://github.com/textileio/go-textile/pull/762
- [x] https://github.com/textileio/go-textile/issues/794
- [x] https://github.com/textileio/go-textile/issues/795
- [x] https://github.com/textileio/go-textile/issues/797
  - [x] https://github.com/textileio/go-textile/issues/799
- [x] https://github.com/textileio/go-textile/issues/809
- [ ] revises docs for textileio/go-textile#812

**Comment by balupton** [comment]
Good point. Will review this week.

**Comment by carsonfarmer** [comment]
I'll document updates required here as I find them (going through tour now):

- `textile threads add` requires --key flag now, should be updated

**Comment by balupton** [comment]
Thanks @carsonfarmer, keep em coming!

**Comment by sanderpick** [comment]
This is a priority. Added to Sprint 13.

**Comment by balupton** [comment]
```
> textile threads add "Any old data" "your.bundle.id.version.Blob" --blob
textile: error: unexpected your.bundle.id.version.Blob, try --help
```

not sure what `your.bundle.id.version.Blob` is meant to be here… a second CLI arg was never documented

---

```
> textile contacts rm "P8rW2RCMn75Dcb96Eiyg8mirb8nL4ruCumvJxKZRfAdpE5fG"
textile: error: expected command but got "rm", try --help
```

- typo in our CLI, had `rn` instead of `rm` - will send PR

**Comment by balupton** [comment]
@carsonfarmer 

> * [ ]  `textile threads add` requires `--key` flag now, should be updated
> *

what command did you run where you got the message that `--key` was required?

**Comment by carsonfarmer** [comment]
Yup, looks like you've got all my findings here @balupton 👍

**Comment by balupton** [comment]
> Yup, looks like you've got all _my_ findings here @balupton 👍, might be others given the links above though?

Yup. Will convert it to a checklist too, so the progress is better communicated.
