### ISSUE TITLE
Command-line docs TOC is broken

### ISSUE THREAD

**Issue by sanderpick** [textileio/docs#95]
This is a regression from switching to HTML based docs for the command line client.

**Comment by balupton** [comment]
Unfortunately, there is no clear solution to this, as documented at:

https://github.com/textileio/docs/commit/6ce6c857f0cb2e4694e8925ee52569e46166b094

> - there is no TOC for the CLI page due to these bugs:
>
>    Python-Markdown/markdown#830
>
>    Python-Markdown/markdown#829

Unless we generate the TOC ourselves.

**Comment by balupton** [comment]
Closed!

https://github.com/textileio/go-textile/pull/847

https://github.com/textileio/docs/pull/100

[Uploading... Screen Shot 2019-07-05 at 5.11.16 am.png ]
